### ISSUE TITLE
[CSharp] Bug Generating code for nullable Enum parameter does not compile

### ISSUE THREAD

**Issue by Havunen** [swagger-api/swagger-codegen-generators#813]
##### Description

When generating C# client from Open Api 3 schema where operation parameter is nullable enum with default value:

```
          {
            "name": "size",
            "in": "query",
            "schema": {
              "default": "Original",
              "$ref": "#/components/schemas/PhotoFileSize"
            },
            "x-position": 3
          }

....


  "components": {
    "schemas": {

      "PhotoFileSize": {
        "type": "string",
        "description": "",
        "x-enumNames": [
          "Original",
          "Avatar"
        ],
        "enum": [
          "Original",
          "Avatar"
        ]
      }
  }
}
```

The generated code does not set default value for the query parameter correctly and it does not define the enum parameter type nullable.

Code generated:
```
byte[] FilesGetUserPhotoFile (string userGuid, string key, PhotoFileSize size = null);
```

Expected result:
The parameter should be typed nullable
```
byte[] FilesGetUserPhotoFile (string userGuid, string key, PhotoFileSize? size = null);
```

originally posted it here:
https://github.com/swagger-api/swagger-codegen/issues/10589

but I believe this is the correct repository for this issue

**Comment by Havunen** [comment]
@HugoMario Is this something you could take a look please. I tried but it gets confusing quickly as I'm not familiar with the code base.

Thank you.

**Comment by Havunen** [comment]
It seems this is fixed in OpenApiTools

**Comment by ozkank** [comment]
Is there any update? 
I am still having these issues on editor.swagger.ui generate client section.

**Comment by Havunen** [comment]
Yeah it seems the whole swagger thing is outdated, I recommend looking into open api tools alternatives

https://github.com/OpenAPITools

**Comment by hrfarrokh** [comment]
Any news on this??
